[package]
name = "smtx_parser"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["staticlib"]

[dependencies]
serde = "1.0.219"
serde_derive = "1.0.219"
serde_cbor = "0.11.2"
flexbuffers = "25.2.10"

[build-dependencies]
cbindgen = "0.28.0"
